### ISSUE TITLE
Issue exporting Face Feature Centroids

### ISSUE THREAD

**Issue by eugenianietov** [BlueQuartzSoftware/DREAM3D#1002]
Hi everyone,

I am using Dream3D to generate a surface mesh of my DCT data, and I'm finding trouble when exporting the face feature data to a file. After generating the mesh and getting all the Triangle Data, I am using the Find Feature Centroids from the Triangle Geometry filter in order to obtain the centroid position of each face. Then, I am using the Export ASCII Data to write these data to a file. However, when I open the file, I am only getting the centroid position for the first 155 surfaces. From then on, the centroid position is always (0,0,0). Conversely, the FaceLabels_0 and 1 and the number of triangles included in each surface are well written in the file. On the other hand, I also exported some data from the Triangle Data container (for every single triangle in the mesh). In this case, the FaceCentroids are adequately written in the file with no problem, even being this file much larger than the Face Feature data. I don't really know if this problem comes from the Face Feature centroid calculation or the data export.... 

Any guidance or help on this issue will be greatly appreciated!! Thanks in advance!

Eugenia

**Comment by imikejackson** [comment]
If you would like the centroid of each triangle, we have the "Generate Triangle Centroids" filter that should be used.

**Comment by eugenianietov** [comment]
Hi Michael,

I used the "Generate Triangle Centroids" to get the centroid of each triangle, and I could export it with no problem with the "Export ASCII Data filter". Everything seems fine with that calculation. The problem comes from the "Find Feature Centroids" data output. I am using this filter in order to obtain the centroid of each surface mesh face, that takes into account all the triangles that belong to each face. When I write these data to a file, I saw that the centroids are written just for the first 155 faces out of 772 faces, the rest appear as just (0,0,0).

I attach the Face Feature Data csv file just in case you want to take a look. Thanks a lot!

Eugenia 
[Top-7_export_FaceFeatureData.csv](https://github.com/BlueQuartzSoftware/DREAM3D/files/9548815/Top-7_export_FaceFeatureData.csv)

**Comment by imikejackson** [comment]
Try the "Find Feature Centroids from Triangle Geometry" filter. I think that is what you are looking for.

**Comment by eugenianietov** [comment]
I already used that filter and it does the job. The problem comes when I try to export the data with the "Export ASCII Data filter" as I said before. It only writes the centroids of the first 155 faces out of 772 faces; the rest appear as just (0,0,0) and this is wrong. You can check it in the provided csv file in my previous comment.

**Comment by imikejackson** [comment]
@eugenianietov This was fixed in the recen6 6.5.167 release. Please give that one a try.
