### ISSUE TITLE
Possible Crashing bugs in FindFeatureHistogram Filter

### ISSUE THREAD

**Issue by saconnell** [BlueQuartzSoftware/DREAM3D#257]
1. Zero or a negative number could be entered for number of bins. This could lead to divide by zero or negative bins. In the new file CalculateArrayHistogram.cpp, I added a check for <=0 and set the default to -1 to force the user to set a positive number. We also changed the text box outline for a blank in the int widget.
2. The histogram array has to be initialized to zero. The starting point for each element in the array has to be zero for the increment.
3. For your histogram, should multi-component arrays be allowed:

**Comment by imikejackson** [comment]
This filter has been marked private and so can not be used by users.
