### ISSUE TITLE
Standardize error codes

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/DREAM3D#369]
DREAM.3D currently uses arbitrary error codes, which makes documenting what a particular error code means difficult. An error code system/policy should be devised and documented and then implemented to make error codes more consistent.

**Comment by imikejackson** [comment]
The error codes are there for the developer and not really intended for the user other than to communicate the error back to the developer. Having unique error codes allows the developer to quickly find the error in the source codes.
