### ISSUE TITLE
Crash when reading SPPARKS output files

### ISSUE THREAD

**Issue by mathematicus** [BlueQuartzSoftware/DREAM3D#413]
Dream3D crashes whenever I attempt to read a SPPARKS output file. The program exhibits two types of crash behaviors. 

One occurs immediately upon selecting the file. This usually seems to happen when the file is slightly differently formatted than expect.

The second type of crash occurs when the Read SPParks Text File Filter is executed. The status bar appears to advance a little, but the program then crashes.

I am running DREAM3D version 6.1.77 on Mac OS 10.10.4. I have included the first 20 lines of my input file below.

ITEM: TIMESTEP
57        570
ITEM: NUMBER OF ATOMS
1000000
ITEM: BOX BOUNDS
0 100
0 100
0 100
ITEM: ATOMS id i1 d1 x y z 
1 118453 0 0 0 0 
2 118453 0 1 0 0 
3 118453 0 2 0 0 
4 118453 0 3 0 0 
5 148861 0 4 0 0 
6 148861 0 5 0 0 
7 148861 0 6 0 0 
8 148861 0 7 0 0 
9 101910 0 8 0 0 
10 101910 0 9 0 0 
11 151190 0 10 0 0 
12 196944 0 11 0 0 
13 196944 0 12 0 0 
14 77905 0 13 0 0 
15 164585 0 14 0 0 
16 38001 0 15 0 0 
17 164585 0 16 0 0 
18 117272 0 17 0 0 
19 164585 0 18 0 0 
20 182364 0 19 0 0

**Comment by sdonegan** [comment]
Thanks for the report, we'll look into the problem.  It is probably in the kinds of data we currently support parsing, which is almost certainly an incorrect subset of what SPPARKS can output.

**Comment by mathematicus** [comment]
Thanks. I just started a project where I plan to work extensively with both SPPARKS and DREAM3D. SPPARKS allows of the output of a variable number of data columns and that seems tricky to handle. I will look into it a little more and see if I can figure out the correct format.

**Comment by imikejackson** [comment]
The type of file that needs to be read is a Sparks DUMP file. The code was changed a while ago to read this kind of file and the class names have now been changed to reflect the types of SPParks files that are either read or written.
