### ISSUE TITLE
Add ability to read all slices from EDAX HDF5 file as a stack of EBSD slice data

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/DREAM3D#435]
The current Read EDAX H5 EBSD filter only allows the user to select a single set of data. The filter should allow the user to import all data from the HDF5 file.

**Comment by sdonegan** [comment]
Will need to determine the mapping between the recommended transformations and the actual transformations, and then apply them at import (if the user elects to do so, see ReadH5EBSD for template).
