### ISSUE TITLE
Implement Potts model coarsening code

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/DREAM3D#479]
Implement a Potts model coarsening code in the SyntheticBuilding plugin.  Model would most likely be purely stochastic to start, with options for periodic boundaries and no spin flipping for the 0 spin.

**Comment by wlenthe** [comment]
this would be easy to implement with the [CA plugin](https://github.com/dream3d/DREAM3D/tree/attributeMatrix/Source/Plugins/CellularAutomata) if it gets ported to the current branch

**Comment by imikejackson** [comment]
Implemented in the DREAM3D Review plugin.
