### ISSUE TITLE
Expose and Update Filter to Read Vector Image Stack

### ISSUE THREAD

**Issue by mgroeber** [BlueQuartzSoftware/DREAM3D#498]
The Import Vector Images (3D Stack) filter is currently private and needs to be put back to public, but first needs to be updated to use ITK instead of Qt to load the images.  After this is done, the Qt versions of Import Images (3D Stack) and Import Vector Images (3D Stack) should be considered for removal, since they only work on 8bit or 32bit rgba images.

**Comment by thewtex** [comment]
CC: @vovythevov

**Comment by imikejackson** [comment]
Started conversion of filter, filter parameter and widget. Moved from ImageProcessing to ITKImageProcessing. Still need to actually use Itk classes to read the file.

**Comment by imikejackson** [comment]
Fixed at some point in early 2018.
