### ISSUE TITLE
Back Button does not work in the DREAM3D Help dialog

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/DREAM3D#512]

**Comment by joeykleingers** [comment]
The back button does not work in the help dialog, even though the appropriate slot gets hit when the button is pressed, and the correct "back" slot is being called in that slot to load the previous page.

**Comment by joeykleingers** [comment]
Posted to the Qt list and waiting for a response.

**Comment by imikejackson** [comment]
The response from the Qt list is that the feature is broken in Qt 5.4. and Qt 5.5 but is supposedly fixed in Qt 5.6.
