### ISSUE TITLE
Dream.3D Help ver. 6.2.x freezes in Windows 7

### ISSUE THREAD

**Issue by latmarat** [BlueQuartzSoftware/DREAM3D#526]
This happens to me starting from ver. 6.2.0, including the last release (6.2.327). 
Dream.3D Help ver. 6.1.77 works fine in the same machine.

![frozendream](https://cloud.githubusercontent.com/assets/11688736/12355211/7c91a838-bb9b-11e5-8b1e-cbe63931dab1.png)

The same error appears upon calling help for any filter.

**Comment by joeykleingers** [comment]
We think we have fixed this issue.  Please redownload DREAM3D 6.2.327 from the website and see if it works now.
