### ISSUE TITLE
Decimal values are not always read correctly

### ISSUE THREAD

**Issue by kglowins** [BlueQuartzSoftware/DREAM3D#529]
I encounterd the same problem as in https://github.com/dream3d/DREAM3D/issues/476
in Convert Hexagonal Grid Data to Square Grid Data (TSL - .ang) filter. When I specify the X or Y spacing to be, e.g., 0,4 (note the comma) it is (most likely) read as zero.
In the headers of the resulting ang files, the X and/or Y step is 0, and there is no data in the file below the header.

**Comment by imikejackson** [comment]
Thanks for the report. We will try to update those places that we missed at some point in the future. Please keep the reports coming.. 
--
Mike Jackson  [mike.jackson@bluequartz.net]

**Comment by imikejackson** [comment]
These issues should now be resolved. Can you check on your system to ensure the fixes have been put in place correctly?
