### ISSUE TITLE
Bugs in cmake templates

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/DREAM3D#545]
Two errors in SIMPLView\Source\Applications\DevHelper\Template\:
+ file CMakeLists.txt.in, line 235: SIMPLViewWidgetsLib should be replaced by SVWidgetsLib.
+ file SourceList.cmake.under FilterParameterWidgets folder, lines 26 and 27, Core is missing in the paths

**Comment by sdonegan** [comment]
Thanks for the bug report; these issues have been fixed by commit 0fbbd2bfe14f2ff21084c12db738c8e93f6675ed.
