### ISSUE TITLE
Calling initalizeTuple with incorrect second argument

### ISSUE THREAD

**Issue by OndrejSedivy** [BlueQuartzSoftware/DREAM3D#550]
Function initializeTuple in DataArray.hpp expects pointer as its second argument but it is incorrectly called with a constant value on a few places. For instance, Add Bad Data does not work properly due to this bug, the same problem occurs in AdaptiveAlignment.cpp, RotateSampleRefFrame.cpp and WarpRegularGrid.cpp.

**Comment by imikejackson** [comment]
Thank you for the report. We will take a look at this issue as we are preparing a new release.

**Comment by OndrejSedivy** [comment]
Well. I have corrected that in AdaptiveAlignment.cpp.
