### ISSUE TITLE
Wrong writing of IPF color in vtk

### ISSUE THREAD

**Issue by OndrejSedivy** [BlueQuartzSoftware/DREAM3D#552]
Selecting the IPF color array for writing in ascii format by Vtk Rectilinear Grid Writer leads to a wrong output. The header is written correctly but instead of the data values, a sequence of meaningless symbols (maybe binaries) is written. Writing to a binary file seems to be working fine.

**Comment by imikejackson** [comment]
This is probably a bug in the ASCII support for those kinds of arrays. Until we can address this issue please write the VTK files in Binary.
