### ISSUE TITLE
Searchable help

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/DREAM3D#570]
Hello,

This is only a suggestion about having, if possible, a searchable help. That would be very useful when looking for a filter.

Regards
Stéphane

**Comment by imikejackson** [comment]
The development team will be looking into this issue in the coming time ahead. During the development process we have pushed the help files up to the web site and allowed google to index them. You can go to google and try the following search:

site:dream3d.bluequartz.net/binaries/Help/DREAM3D  EDAX

Which should show you all the filters that have "EDAX" in them. As we work on this feature we would encourage you to provide feedback so the development team can produce the best user experience.

**Comment by imikejackson** [comment]
Take a look at issue #570.
