### ISSUE TITLE
Precipitate name missing in PhaseName StringArray

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/DREAM3D#592]
Hello,

We have built a filter that reads in, as required object, the PhaseName StringArray generated by the StatsGenerator.
We are using the prebuilt pipeline "Two Phase Cubic Hexagonal Particles Equiaxed.json". There we give a name to both the primary phase (e.g. phase) and the precipitate (e.g. ppt).
However, in our filter, when we read in the PhaseName, only the former appears (i.e. phase) but an empty field appears for the precipitate although the StringArray of the array is correct (i.e. 3).
Thanks.

Regards
Stéphane

**Comment by imikejackson** [comment]
I have updated the codes with the last push to the repo. Can you please test the changes with your filter so that you are getting the expected results?

**Comment by dumoulins** [comment]
Hi Michael,

That bug is solved. I can now read the ppt name in PhaseName.
Thanks. You can close that issue.

Regards
Stéphane
