### ISSUE TITLE
Changes to StatsGenerator from Saved Pipeline not saved after load and edit.

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/DREAM3D#593]
Hi,

I have experienced several times some problems with the StatsGenerator.
When I open a pipeline that I built earlier and make a change in the StatsGenerator (e.g. Fraction, Phase Name), save it, close it and then open it again, none of my changes are kept.
The only way to have them stored is either to build the pipeline from scratch once more or to edit the json file and make the modifications there if possible.
I believe there is a bug somewhere.

Stephane

**Comment by imikejackson** [comment]
I can reproduce the issue here on our machines. I will take a look in the coming days. There has been a lot of refactoring of StatsGenerator in the last few months so these types of bugs are typical. Thank you for reporting this issue.

**Comment by imikejackson** [comment]
Stephane, 
   Please try out the latest develop branch. I believe I have found and fixed the issue but I would like some testing outside of BlueQuartz before I close the issue.

**Comment by dumoulins** [comment]
Hi again,

This seems to work now.
Thanks a lot. I believe you can close the issue.

Regards
Stéphane
