### ISSUE TITLE
ang import error for last point

### ISSUE THREAD

**Issue by MarDiehl** [BlueQuartzSoftware/DREAM3D#597]
I'm using DREAM3D to convert from ang to DREAM3D (HDF5, XDMF).
The last point (for Confidence Index, Euler Angles, Image Quality) gets always a value of zero.
I've inspected the HDF5 file in HDFview, at it is really the binary data that is wrong (not just visualization in paraview). I would assume it's related to 0 vs. 1 based indexing.
I can reproduce this behavior for different ang datasets. DREAM3D version is 6.3.29.

Pipeline and a small example are given:
[01-100_c_ang.txt](https://github.com/BlueQuartzSoftware/DREAM3D/files/597902/01-100_c_ang.txt)
[ConvertToDREAM3D_json.txt](https://github.com/BlueQuartzSoftware/DREAM3D/files/597903/ConvertToDREAM3D_json.txt)

The following image from paraview illustrates this behavior for a larger dataset
![iq](https://cloud.githubusercontent.com/assets/6196733/20397703/042ca0d6-aceb-11e6-94b2-ca466313773f.png)

**Comment by imikejackson** [comment]
Thank you for reporting this issue. I have replicated the bug and understand the failure point. For now you should be able to add an extra line of data at the end of your .ang file and see if that allows the last line to be read but I think this may have other issues (like crashing DREAM.3D). We will take a look and see if this bug warrants a new build to be issued.

Thank you for reporting this bug.

**Comment by MarDiehl** [comment]
Thanks for the quick reply.
Unfortunately, adding an extra line does not work as the number of points is than higher than expected from the header and the filter exists with error code -600.
As a follow up, since I was also writing converters for ang files, I would not recommend to parse the expected number of points from the header. This is simply because the header information and the actual number of points might not match when exporting from TSL OIM Analysis (might be related to cropping data or converting hex<->cub, I could not find a pattern yet). While this is certainly a bug in the TSL software and can be fixed by editing the ang file with a text editor, one can simply avoid trouble by determine the grid information from the actual scan data. Since the coordinates are always included in ang files, the grid spacing and the number of points in x and y direction can easily be determined independently of the header information. For hex grids, this is of course a little bit more involved than for pixel data.

**Comment by imikejackson** [comment]
Can you try the latest nightly build of DREAM.3D for your system and report back if the problem is fixed. I was able to fix it on our end an put in a test that should verify if we are correctly reading the file.

**Comment by MarDiehl** [comment]
Dear Mike,
thanks for the quick fix. I can confirm that the nightly build fixes the issue on my system (Windows 7).

**Comment by imikejackson** [comment]
Thanks for the testing. We are hoping to get a release done in December with all of these fixes rolled into it. I would stick with a nightly until a release comes out. They are generally stable but have been known to break occasionally.

**Comment by imikejackson** [comment]
Users reported issues with their .ang files. Investigating the issue.

**Comment by imikejackson** [comment]
Issue resolved as before. The user reporting the issue had a malformed .ang file where the header did not match the rows of data in the .ang file.
