### ISSUE TITLE
ExtractComponentAsArray allows negative component ID

### ISSUE THREAD

**Issue by mmarineBlueQuartz** [BlueQuartzSoftware/DREAM3D#613]
ExtractComponentAsArray filter does not throw errors if a negative component ID is specified and fills the initial values in the new array with preexisting data depending on the ID.  Larger negative numbers offset the extracted array by larger amounts.

**Comment by imikejackson** [comment]
Moved to https://github.com/BlueQuartzSoftware/SIMPL/issues/12 since this is a SIMPL issue and not a DREAM.3D issue.
