### ISSUE TITLE
Generate string array

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/DREAM3D#627]
Strings are becoming used/required in different filters (e.g PhaseName) and, depending on the pipeline, they might not be defined.
Therefore, it would be very useful to allow the user to create string arrays. This could be either as an added feature in the filter "Create Data Array" or as a new filter.

**Comment by imikejackson** [comment]
Looking at initial code I think we should just have the number of components be 1, which means we take it out of the user's hands as a parameter. In fact, just hard code the number of components to 1 in the filter code and remove the parameter to set it.

**Comment by imikejackson** [comment]
Also not sure if initializeArray() actually does anything? Have you pushed all the latest code?
