### ISSUE TITLE
Error tuple count in "Read ASCII Data" filter

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/DREAM3D#628]
There is an error in how the number of tuples are counted in the "Read ASCII Data" filter.
 For example, if the ASCII data file contains 1000 lines among which 10 are not read ("Start import at row: 10) then in the "Attribute Matrix Settings" window it shows 1000 in "Total Tuples" and 1010 in "Line Count" - while it should be 990 and 1000, respectively - and a message displays "The current tuple dimensions do not match the total number of tuplres".

**Comment by dumoulins** [comment]
There is an error in how the number of tuples are counted in the "Read ASCII Data" filter.
For example, if the ASCII data file contains 1000 lines among which 10 are not read ("Start import at row: 10) then in the "Attribute Matrix Settings" window it shows 1000 in "Total Tuples" and 1010 in "Line Count" - while it should be 990 and 1000, respectively - and a message displays "The current tuple dimensions do not match the total number of tuplres".

**Comment by imikejackson** [comment]
Stephane, Can you try out the latest code on your end and let us know if the changes help clarify the information to the user?

**Comment by dumoulins** [comment]
Hi Michael,

Thank you for your prompt reply.
I believe I was not very clear in my comments. The filter was rather clear but I thought that by default the "Total attribute matrix tuples" would be equal to the "total lines imported".

Regards
Stéphane

**Comment by joeykleingers** [comment]
The "Total Attribute Matrix Tuples" label has been removed, because it was causing too much confusion.  It was primarily just supposed to be the count of how many tuples were input based on the tuple dimensions that were input, but it makes more sense to simplify the user interface by leaving that information out.
