### ISSUE TITLE
Dream3d crashes when calculating neighbor misorientations

### ISSUE THREAD

**Issue by Yufeng-shen** [BlueQuartzSoftware/DREAM3D#636]
Hi, 
I'm using Dream3d v6.3.29 on Linux 64bit. My pipeline and data are here: [https://www.dropbox.com/s/huo3m20lrbwrg91/misorientation.zip?dl=0](url)

Thanks!
Yufeng

**Comment by imikejackson** [comment]
Fixed with https://github.com/BlueQuartzSoftware/DREAM3D/commit/d943276375b4b46d760ba016d75e26ef19a23d70

Please try the next nightly build which will have this fix. Nightly builds can be downloaded from http://dream3d.bluequartz.net/binaries/experimental/
