### ISSUE TITLE
When opening pipeline files, empty pipeline window shold be replaced with the pipeline file.

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/DREAM3D#644]
Start DREAM.3D. A new empty window appears.
Select a pipeline either through opening, recent files, bookmarks.
That pipeline opens, but the other Empty Pipeline Window still stays around.
Make the empty window go away.

**Comment by imikejackson** [comment]
Reviewing the initial code can you test the following:

open DREAM3D
Open a pipeline, any pipeline file.
remove all the filters so the pipeline is empty.
Open another pipeline. From the looks of the code the first window should go away which is probably NOT what we want.

Maybe check for the isModified() property also? Maybe we need another property on the window that flags it as untitled and never modified? With those 2 flags we can reliably close the window?


Also, there is a SIMPViewMacApplication. Do we need any changes in that class?

**Comment by mmarineBlueQuartz** [comment]
Closed.  A landing page will be created instead.
