### ISSUE TITLE
CMake creates VS solutions that contain multiple projects with the same name

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/DREAM3D#650]
When CMake creates a VS solution, it defines two projects both with the name "DREAM3D": the main DREAM3D application project, and another that holds a test folder for two executable tests, the FilterParameterCallbackExample and the PreflightTest.  Under CMake 3.5 or less, the solution may still be opened in VS despite the issues, though a warning is thrown.  Under CMake 3.7.2 (current stable release), the solution is invalid and one of the "DREAM3D" projects will not be loaded. 

The source of the issue seems to be in the Test/CMakeLists.txt file, lines 34 and 48 in the corresponding AddSIMPLUnitTest calls, which declare the target folder to the "DREAM3D/Test".  Changing these lines to some other project name (e.g., "DREAM3DTest/Test") fixes the issue (using CMake 3.7.2 & VS 2013 Express).  Recommend changing these folder names to something other than "DREAM3D" to fix the issue.

**Comment by imikejackson** [comment]
Fixed with latest commit.
