### ISSUE TITLE
Steiner Compact filter throws errors without changing color in the pipeline view

### ISSUE THREAD

**Issue by mmarineBlueQuartz** [BlueQuartzSoftware/DREAM3D#657]
Errors are correctly marked in Pipeline Issues but the number label will not change to red.  At a glance, the filter is not throwing errors.

**Comment by imikejackson** [comment]
This is a filter in the Anisotropy plugin [Anisotropy](http://www.github.com/dream3d/anisotropy) that was fixed with its commit https://github.com/dream3d/Anisotropy/commit/d8393f1490e752b822b1db2ca200acd7710e3632
