### ISSUE TITLE
StatsGeneratorODFWidget attempts to use a class from SVWidgetsLib that is not exported

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/DREAM3D#673]
Specifically, StatsGeneratorODFWidget attempts to instantiate a ProgressDialog from SVWidgetsLib, but ProgressDialog does not currently have the correct export macro (SVWidgetsLib_EXPORT); this causes a link error on Windows.  Commit dd62d39 from the SIMPL repo seems to indicate that the ProgressDialog may have some unwanted interactions, so a fix would be to just comment out the usage of ProgressDialog in StatsGeneratorODFWidget, which occurs in the `calculateODF()` function (bug is here on DREAM3D for that reason).

Another fix is to add the export macro to ProgressDialog over in the SIMPL repo.

**Comment by imikejackson** [comment]
Fixed by adding the export macro in the source code.
