### ISSUE TITLE
Create Geometry does not remove arrays from the data structure

### ISSUE THREAD

**Issue by mmarineBlueQuartz** [BlueQuartzSoftware/DREAM3D#740]
The Create Geometry filter in DREAM3DReview does not remove any DataArray describing the geometry from the DataStructure. Shared vertex lists, triangle lists, quadrilateral lists, etc. should be moved to the geometry.  Any filter that needs access to these arrays should do so through the created geometry.

**Comment by imikejackson** [comment]
Transferring bug to https://github.com/dream3d/DREAM3DReview/issues/3
