### ISSUE TITLE
Create Geometry has incorrect DataArray requirements

### ISSUE THREAD

**Issue by mmarineBlueQuartz** [BlueQuartzSoftware/DREAM3D#741]
The FilterInputWidget for Create Geometry in DREAM3DReview requires a 2-component array for Triangle List under triangle geometry, but the filter requires a 3-component array and errors out.  The only way to select the correct array in the GUI is to change the correct array to 2 components, select the array, and then change the array to 3 components.

**Comment by imikejackson** [comment]
Issue moved to proper repository.

https://github.com/dream3d/DREAM3DReview/issues/1
