### ISSUE TITLE
Dream3D crashes when generating ensemble statistics

### ISSUE THREAD

**Issue by tashton95** [BlueQuartzSoftware/DREAM3D#773]
I am running a pipeline to generate morphological statistics in a 3D image stack, but the program crashes when it reaches the Generate Ensemble Statistics filter. The same thing happens when using a single image as well; I've tested both png and bmp formats to see if it's an image type problem, but the crash still occurs. I am using the latest version of Dream3D for Windows, but the same crash happens using v6.3 for OSX. The pipeline leading up to Generate Ensemble Statistics runs as follows:

ITK::Import Image Stack
Extract Component as Attribute Array
Threshold Objects
Create Data Array
Replace Value in Array (Conditional)
Export Data (ASCII Text)
Segment Features (Scalar)
Find Feature Phases
Create Attribute Matrix
Find Feature Neighbors
Find Feature Centroids
Find Surface Features
Find Feature Sizes
Find Feature Shapes
Find Feature Neighborhoods
Generate Ensemble Statistics
etc...

The pipeline runs perfectly for every other filter, and it outputs the expected data well enough, but I'm not sure how to stop the crash. Any and all help is appreciated

**Comment by imikejackson** [comment]
There were a few problems in the way that the pipeline was setup.  I will just make some notes as I go through the pipeline.

There is a “Color to Gray Scale” filter that you should use instead of just grabbing the first component of an RGB Array.
 
In the “Create Data Array” filter you create a type of “Unsigned Int 8 bit”. After working through  the pipeline I figured out that you were wanting this as your “Phases” array. Phases need to be Signed Int 32 Bit values. I also initialized all to phase=1. Phase=0 has special meaning in DREAM.3D. Next I also named the output array “Phases” so it is easier to refer to that array later on.
 
Now, basically any filter that asks for Cell Level “Phases” was using instead the FeatureIds which is bad. After the fix from above you can now select the proper value for those input arrays.

**Comment by imikejackson** [comment]
{
    "00": {
        "CellAttributeMatrixName": "CellData",
        "DataContainerName": "ImageDataContainer",
        "FileName": "/Users/mjackson/Desktop/HfAl_2_2.bmp",
        "FilterVersion": "1.0.400",
        "Filter_Enabled": true,
        "Filter_Human_Label": "ITK::Image Reader",
        "Filter_Name": "ITKImageReader",
        "Filter_Uuid": "{653b7b5c-03cb-5b32-8c3e-3637745e5ff6}",
        "ImageDataArrayName": "ImageData"
    },
    "01": {
        "ColorChannel": 0,
        "ColorWeights": {
            "x": 0.21250000596046448,
            "y": 0.715399980545044,
            "z": 0.07209999859333038
        },
        "ConversionAlgorithm": 0,
        "CreateNewAttributeMatrix": 0,
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Color to GrayScale",
        "Filter_Name": "ConvertColorToGrayScale",
        "Filter_Uuid": "{eb5a89c4-4e71-59b1-9719-d10a652d961e}",
        "InputDataArrayVector": [
            {
                "Attribute Matrix Name": "CellData",
                "Data Array Name": "ImageData",
                "Data Container Name": "ImageDataContainer"
            }
        ],
        "OutputArrayPrefix": "GrayScale_",
        "OutputAttributeMatrixName": "GrayScaleData"
    },
    "02": {
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Rename Attribute Array",
        "Filter_Name": "RenameAttributeArray",
        "Filter_Uuid": "{53a5f731-2858-5e3e-bd43-8f2cf45d90ec}",
        "NewArrayName": "Voxels",
        "SelectedArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "GrayScale_ImageData",
            "Data Container Name": "ImageDataContainer"
        }
    },
    "03": {
        "DestinationArrayName": "Mask",
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Threshold Objects",
        "Filter_Name": "MultiThresholdObjects",
        "Filter_Uuid": "{014b7300-cf36-5ede-a751-5faf9b119dae}",
        "SelectedThresholds": [
            {
                "Attribute Array Name": "Voxels",
                "Attribute Matrix Name": "CellData",
                "Comparison Operator": 1,
                "Comparison Value": 150,
                "Data Container Name": "ImageDataContainer"
            }
        ]
    },
    "04": {
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Create Data Array",
        "Filter_Name": "CreateDataArray",
        "Filter_Uuid": "{77f392fb-c1eb-57da-a1b1-e7acf9239fb8}",
        "InitializationRange": {
            "Max": 0,
            "Min": 0
        },
        "InitializationType": 0,
        "InitializationValue": "1",
        "NewArray": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        },
        "NumberOfComponents": 1,
        "ScalarType": 4
    },
    "05": {
        "ConditionalArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Mask",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Replace Value in Array (Conditional)",
        "Filter_Name": "ConditionalSetValue",
        "Filter_Uuid": "{47cafe63-83cc-5826-9521-4fb5bea684ef}",
        "ReplaceValue": 2,
        "SelectedArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        }
    },
    "06": {
        "Delimiter": 0,
        "FileExtension": ".txt",
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Export ASCII Data",
        "Filter_Name": "WriteASCIIData",
        "Filter_Uuid": "{5fbf9204-2c6c-597b-856a-f4612adbac38}",
        "MaxValPerLine": 1,
        "OutputPath": "/Users/intern/Documents",
        "SelectedDataArrayPaths": [
            {
                "Attribute Matrix Name": "CellData",
                "Data Array Name": "ImageData",
                "Data Container Name": "ImageDataContainer"
            },
            {
                "Attribute Matrix Name": "CellData",
                "Data Array Name": "Mask",
                "Data Container Name": "ImageDataContainer"
            },
            {
                "Attribute Matrix Name": "CellData",
                "Data Array Name": "Phases",
                "Data Container Name": "ImageDataContainer"
            },
            {
                "Attribute Matrix Name": "CellData",
                "Data Array Name": "Voxels",
                "Data Container Name": "ImageDataContainer"
            }
        ]
    },
    "07": {
        "ActiveArrayName": "Active",
        "CellFeatureAttributeMatrixName": "CellFeatureData",
        "FeatureIdsArrayName": "FeatureIds",
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Segment Features (Scalar)",
        "Filter_Name": "ScalarSegmentFeatures",
        "Filter_Uuid": "{2c5edebf-95d8-511f-b787-90ee2adf485c}",
        "GoodVoxelsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Mask",
            "Data Container Name": "ImageDataContainer"
        },
        "ScalarArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Voxels",
            "Data Container Name": "ImageDataContainer"
        },
        "ScalarTolerance": 0,
        "UseGoodVoxels": 0
    },
    "08": {
        "CellPhasesArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        },
        "FeatureIdsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "FeatureIds",
            "Data Container Name": "ImageDataContainer"
        },
        "FeaturePhasesArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Feature Phases",
        "Filter_Name": "FindFeaturePhases",
        "Filter_Uuid": "{6334ce16-cea5-5643-83b5-9573805873fa}"
    },
    "09": {
        "AttributeMatrixType": 11,
        "CreatedAttributeMatrix": {
            "Attribute Matrix Name": "EnsembleAttributeMatrix",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Create Attribute Matrix",
        "Filter_Name": "CreateAttributeMatrix",
        "Filter_Uuid": "{93375ef0-7367-5372-addc-baa019b1b341}",
        "TupleDimensions": {
            "Column Headers": [
                "0"
            ],
            "DefaultColCount": 0,
            "DefaultRowCount": 0,
            "HasDynamicCols": false,
            "HasDynamicRows": false,
            "MinColCount": 0,
            "MinRowCount": 0,
            "Row Headers": [
                "0"
            ],
            "Table Data": [
                [
                    3
                ]
            ]
        }
    },
    "10": {
        "BoundaryCellsArrayName": "BoundaryCells",
        "CellFeatureAttributeMatrixPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "FeatureIdsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "FeatureIds",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Feature Neighbors",
        "Filter_Name": "FindNeighbors",
        "Filter_Uuid": "{97cf66f8-7a9b-5ec2-83eb-f8c4c8a17bac}",
        "NeighborListArrayName": "NeighborList",
        "NumNeighborsArrayName": "NumNeighbors",
        "SharedSurfaceAreaListArrayName": "SharedSurfaceAreaList",
        "StoreBoundaryCells": 0,
        "StoreSurfaceFeatures": 0,
        "SurfaceFeaturesArrayName": "SurfaceFeatures"
    },
    "11": {
        "CentroidsArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Centroids",
            "Data Container Name": "ImageDataContainer"
        },
        "FeatureIdsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "FeatureIds",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Feature Centroids",
        "Filter_Name": "FindFeatureCentroids",
        "Filter_Uuid": "{6f8ca36f-2995-5bd3-8672-6b0b80d5b2ca}"
    },
    "12": {
        "FeatureIdsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "FeatureIds",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Surface Features",
        "Filter_Name": "FindSurfaceFeatures",
        "Filter_Uuid": "{d2b0ae3d-686a-5dc0-a844-66bc0dc8f3cb}",
        "SurfaceFeaturesArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "SurfaceFeatures",
            "Data Container Name": "ImageDataContainer"
        }
    },
    "13": {
        "EquivalentDiametersArrayName": "EquivalentDiameters",
        "FeatureAttributeMatrixName": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "FeatureIdsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "FeatureIds",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Feature Sizes",
        "Filter_Name": "FindSizes",
        "Filter_Uuid": "{656f144c-a120-5c3b-bee5-06deab438588}",
        "NumElementsArrayName": "NumElements",
        "SaveElementSizes": 0,
        "VolumesArrayName": "SizeVolumes"
    },
    "14": {
        "AspectRatiosArrayName": "AspectRatios",
        "AxisEulerAnglesArrayName": "AxisEulerAngles",
        "AxisLengthsArrayName": "AxisLengths",
        "CellFeatureAttributeMatrixName": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "CentroidsArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Centroids",
            "Data Container Name": "ImageDataContainer"
        },
        "FeatureIdsArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "FeatureIds",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Feature Shapes",
        "Filter_Name": "FindShapes",
        "Filter_Uuid": "{3b0ababf-9c8d-538d-96af-e40775c4f0ab}",
        "Omega3sArrayName": "Omega3s",
        "VolumesArrayName": "ShapeVolumes"
    },
    "15": {
        "CentroidsArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Centroids",
            "Data Container Name": "ImageDataContainer"
        },
        "EquivalentDiametersArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "EquivalentDiameters",
            "Data Container Name": "ImageDataContainer"
        },
        "FeaturePhasesArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Feature Neighborhoods",
        "Filter_Name": "FindNeighborhoods",
        "Filter_Uuid": "{697ed3de-db33-5dd1-a64b-04fb71e7d63e}",
        "MultiplesOfAverage": 10,
        "NeighborhoodListArrayName": "NeighborhoodList",
        "NeighborhoodsArrayName": "Neighborhoods"
    },
    "16": {
        "AspectRatioDistributionFitType": 0,
        "AspectRatiosArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "AspectRatios",
            "Data Container Name": "ImageDataContainer"
        },
        "AvgQuatsArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "AxisEulerAnglesArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "AxisEulerAngles",
            "Data Container Name": "ImageDataContainer"
        },
        "BiasedFeaturesArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "SurfaceFeatures",
            "Data Container Name": "ImageDataContainer"
        },
        "CalculateAxisODF": 1,
        "CalculateCrystallographicStats": 0,
        "CalculateMDF": 0,
        "CalculateMorphologicalStats": 1,
        "CalculateODF": 0,
        "CellEnsembleAttributeMatrixPath": {
            "Attribute Matrix Name": "EnsembleAttributeMatrix",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "ComputeAspectRatioDistribution": 1,
        "ComputeNeighborhoodDistribution": 1,
        "ComputeOmega3Distribution": 1,
        "ComputeSizeDistribution": 1,
        "CrystalStructuresArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "EquivalentDiametersArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "EquivalentDiameters",
            "Data Container Name": "ImageDataContainer"
        },
        "FeatureEulerAnglesArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "FeaturePhasesArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Generate Ensemble Statistics",
        "Filter_Name": "GenerateEnsembleStatistics",
        "Filter_Uuid": "{19a1cb76-6b46-528d-b629-1af5f1d6344c}",
        "IncludeRadialDistFunc": 0,
        "MaxMinRDFArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": ""
        },
        "NeighborListArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "NeighborList",
            "Data Container Name": "ImageDataContainer"
        },
        "NeighborhoodDistributionFitType": 1,
        "NeighborhoodsArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Neighborhoods",
            "Data Container Name": "ImageDataContainer"
        },
        "Omega3DistributionFitType": 0,
        "Omega3sArrayPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "Omega3s",
            "Data Container Name": "ImageDataContainer"
        },
        "PhaseTypeArray": [
            999,
            0,
            0
        ],
        "PhaseTypesArrayName": "PhaseTypes",
        "RDFArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": ""
        },
        "SharedSurfaceAreaListArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "SizeCorrelationResolution": 0.10000000149011612,
        "SizeDistributionFitType": 1,
        "StatisticsArrayName": "Statistics",
        "SurfaceFeaturesArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "VolumesArrayPath": {
            "Attribute Matrix Name": "",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        }
    },
    "17": {
        "CellPhasesArrayPath": {
            "Attribute Matrix Name": "CellData",
            "Data Array Name": "Phases",
            "Data Container Name": "ImageDataContainer"
        },
        "FilterVersion": "6.4.335",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Find Volume Fractions of Ensembles",
        "Filter_Name": "FindVolFractions",
        "Filter_Uuid": "{68246a67-7f32-5c80-815a-bec82008d7bc}",
        "VolFractionsArrayPath": {
            "Attribute Matrix Name": "EnsembleAttributeMatrix",
            "Data Array Name": "VolFractions",
            "Data Container Name": "ImageDataContainer"
        }
    },
    "18": {
        "Delimiter": 0,
        "FileExtension": ".txt",
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Export ASCII Data",
        "Filter_Name": "WriteASCIIData",
        "Filter_Uuid": "{5fbf9204-2c6c-597b-856a-f4612adbac38}",
        "MaxValPerLine": 1,
        "OutputPath": "/Users/mjackson/Desktop",
        "SelectedDataArrayPaths": [
            {
                "Attribute Matrix Name": "EnsembleAttributeMatrix",
                "Data Array Name": "PhaseTypes",
                "Data Container Name": "ImageDataContainer"
            },
            {
                "Attribute Matrix Name": "EnsembleAttributeMatrix",
                "Data Array Name": "VolFractions",
                "Data Container Name": "ImageDataContainer"
            }
        ]
    },
    "19": {
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Write DREAM.3D Data File",
        "Filter_Name": "DataContainerWriter",
        "Filter_Uuid": "{3fcd4c43-9d75-5b86-aad4-4441bc914f37}",
        "OutputFile": "/Users/mjackson/Destop/CirclesStatistics.dream3d",
        "WriteTimeSeries": 0,
        "WriteXdmfFile": 1
    },
    "20": {
        "CellFeatureAttributeMatrixPath": {
            "Attribute Matrix Name": "CellFeatureData",
            "Data Array Name": "",
            "Data Container Name": "ImageDataContainer"
        },
        "DelimiterChoice": 0,
        "FeatureDataFile": "/Users/mjackson/Destop/FeatureData.csv",
        "FilterVersion": "1.0.361",
        "Filter_Enabled": true,
        "Filter_Human_Label": "Export Feature Data as CSV File",
        "Filter_Name": "FeatureDataCSVWriter",
        "Filter_Uuid": "{737b8d5a-8622-50f9-9a8a-bfdb57608891}",
        "WriteNeighborListData": 0,
        "WriteNumFeaturesLine": 1
    },
    "PipelineBuilder": {
        "Name": "FeatureStatistics_3",
        "Number_Filters": 21,
        "Version": 6
    }
}
