### ISSUE TITLE
Parallelize Find Feature Neighborhoods

### ISSUE THREAD

**Issue by tuks188** [BlueQuartzSoftware/DREAM3D#794]
Implement a parallel algorithm (using TBB) for Find Feature Neighborhoods. It is a bottleneck in the MTR pipeline.

**Comment by imikejackson** [comment]
How easy is the algorithm? Is it "embarrassingly parallel? I am not familiar with that code block.

**Comment by tuks188** [comment]
I think it is "embarrassingly parallel" (i.e., feature neighborhoods can all be determined independent of one another). Do you have a good example filter that I can look to for reference?

**Comment by imikejackson** [comment]
Generate IPF Colors comes to mind.

**Comment by imikejackson** [comment]
Looking at the algorithm if you parallelize the algorithm naively you are going to be simultaneously pushing back on vectors which is going to lead to bad results. The easy fix is to create a critical section to add the feature pairs into each others lists. The better solution would be some sort of map-reduce algorithm or have independent vector of vectors then combine all of those at the end of the run into a single vector of vectors.

TBB has the "concurrent_vector<T>" type that could probably be used.

**Comment by tuks188** [comment]
Ok, thanks for the tips. I'll run with it for a bit and let you know.

**Comment by imikejackson** [comment]
I just did a quick implementation. I am definitely running all the CPUs but no idea if the output is correct. I would need to compare against the current release version to get at least a basic sanity check. I have an MTR data set that has about 289,000 features which is a nice test.

**Comment by imikejackson** [comment]
Take a look at the feature/794_Parallelize_FindNeighborhood branch.

**Comment by tuks188** [comment]
I did a comparison w/ and w/o the parallel implementation of an MTR dataset. Visually (in Paraview) the output looks the same. Let me know if a more rigorous test is needed. Otherwise, I'd say go ahead and merge this into develop.

**Comment by imikejackson** [comment]
I think we should be able to devise a test where we prepare the data set up to the point of running the Neighborhood filter and then save the file. We can then run the Neighborhood filter in parallel and serial saving the output of each one and do a value comparison of the 2 data sets?

Sometimes things get past visually inspecting. I would like to have a more rigorous test suite and have it automated to the point where we could run it on a nightly basis. 

We could add an option to the filter to run in parallel or serial which would help with the test.

**Comment by tuks188** [comment]
I have posed very simple neighborhood tests in the past. It could be entered directly into the test file so you wouldn't need to carry around an intermediate file. I'll try my hand at implementing this. Is it good enough to compare the parallel to the serial or do we also need a verified result in case they're both wrong but equally wrong?

Put a parallel/serial option in is easy enough. I'll do that.

**Comment by imikejackson** [comment]
Before I leave behind the previous serial version I would like to verify that the new implementation running in serial gives the same results as the previous serial implementation. Then we can also verify the parallel version.

Does the new parallel version give a good speed up? It looks like there was a lot of hits to the semaphore being used to lock access to the vector of vectors.

**Comment by tuks188** [comment]
The one comparison I made was an "overnight" dataset took about 45 mins, which I would characterize as a good speedup.
