### ISSUE TITLE
Disambiguate AxisLengths In Find Feature Shapes

### ISSUE THREAD

**Issue by tuks188** [BlueQuartzSoftware/DREAM3D#809]
The documentation reads "Axis lengths (a, b, c) for best-fit ellipsoid to Feature," which is correct yet somewhat misleading as a, b, and c are semi-axis lengths (I have confirmed this in the source code). I recommend either changing the subject line to "Semi-axis lengths (a, b, c) for best-fit ellipsoid to Feature" or changing the Feature Attribute Array Default Name from "AxisLengths" to "SemiAxisLengths." The latter option may provide more clarity than the former.

**Comment by imikejackson** [comment]
Go ahead and update the documentation/filter parameters and put in a pull request for the change. I'll take a look at it and push it through.

**Comment by tuks188** [comment]
Done. Let me know if I did it correctly.

**Comment by imikejackson** [comment]
Not quite. You need to put the pull request by going to your fork of DREAM3D and clicking the "Pull Request" link. See attached image.

![screen shot 2018-07-21 at 10 41 40 am](https://user-images.githubusercontent.com/5182396/43036597-c1177cde-8cd2-11e8-90a8-64785bff0197.png)

**Comment by tuks188** [comment]
Done!
