### ISSUE TITLE
Add default option for converting angles from degrees to radians in ReadCtfData

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/DREAM3D#895]
Several reports from industry have led to significant issues regarding importing CTF data using the ReadCtfData filter and not understanding that the Euler angles need to be converted to radians for further processing.

I suggest that we add a checkbox to the filter, that is on by default, to convert the angles from degrees to radians.  Then a user that has a non-standard CTF file with radians can still un-check it for proper execution.

**Comment by imikejackson** [comment]
Sounds like a good enhancement.
