### ISSUE TITLE
ITK Rgb to Luminance over writes existing color data

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/DREAM3D#956]
The filter asks for an output array but the filter will in fact over write the original data. This filter needs to be fixed to make clear what is going to happen.

This effects 6.5.138 and current development.

**Comment by joeykleingers** [comment]
Update filter so that it creates a brand new array instead of overwriting an existing array.

**Comment by joeykleingers** [comment]
Moved to ITKImageProcessing repo: https://github.com/BlueQuartzSoftware/ITKImageProcessing/issues/193
