### ISSUE TITLE
Too much memory just open software.

### ISSUE THREAD

**Issue by Adam-S-Yanxuan** [BlueQuartzSoftware/DREAM3D#963]
I didn't do anything more than open this software in win10.
Then, It takes me 3GB memories, and then crashed.
![image](https://user-images.githubusercontent.com/44885484/103324723-adae8900-4a83-11eb-9190-79c1887df027.png)

![image](https://user-images.githubusercontent.com/44885484/103324773-dafb3700-4a83-11eb-95be-7d6cc6901a7a.png)

**Comment by imikejackson** [comment]
Which version of DREAM.3D are you running?

**Comment by Adam-S-Yanxuan** [comment]
Hello, Jackson.
The version is 6.5.141. Win64.

**Comment by imikejackson** [comment]
We have Windows 10 Versions 2004 on several machines and DREAM.3D takes a normal amount of memory on those machines. All machines are U.S.A locale. Maybe there is an interaction with your native language that we are not aware of.
