### ISSUE TITLE
0 spacing along Z direction when use VTK STRUCTURED_POINTS Importer

### ISSUE THREAD

**Issue by fangchizhou** [BlueQuartzSoftware/DREAM3D#973]
I tried to import the example vtk file shows below, and when I check the geometry information, it shows 0 spacing along z although it should be 1.

# vtk DataFile Version 2.0
GrainIds Stored in Vtk File
ASCII
DATASET STRUCTURED_POINTS
DIMENSIONS 3 4 6
SPACING 1 1 1
ORIGIN 0 0 0
POINT_DATA 72
SCALARS GrainIds char 1
LOOKUP_TABLE default
0 0 0 0 0 0 0 0 0 0 0 0
0 5 10 15 20 25 25 20 15
10 5 0 0 10 20 30 40 50
50 40 30 20 10 0 0 10 20
30 40 50 50 40 30 20 10 0
0 5 10 15 20 25 25 20 15
10 5 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by imikejackson** [comment]
Thank you for reporting this error. I have been able to reproduce the issue. A workaround until a fix can be posted would be to use the "Set Origin and Resolution" filter to adjust the Resolution/Spacing value in the Z Direction.

**Comment by imikejackson** [comment]
The 6.5 Branch needs the fix.

The 6.6 Branch needs broader fixes as the filter will simply not run and gets stuck in a loop somewhere.

**Comment by fangchizhou** [comment]
Thank you very much for your prompt reply.

Regards
Chizhou



-------- 原始邮件 --------
发件人： Michael Jackson ***@***.***>
日期： 2021年3月24日周三 下午1:01
收件人： BlueQuartzSoftware/DREAM3D ***@***.***>
抄送： fangchizhou ***@***.***>, Author ***@***.***>
主 题： Re: [BlueQuartzSoftware/DREAM3D] 0 spacing along Z direction when usee VTK STRUCTURED_POINTS Importer (#973)

Thank you for reporting this error. I have been able to reproduce the issue. A workaround until a fix can be posted would be to use the "Set Origin and Resolution" filter to adjust the Resolution/Spacing value in the Z Direction.

―

**Comment by imikejackson** [comment]
The 6.6 branch was partially fixed by commit a09250cbbe8fd82d18dbcc32ad3ed50585a5cde4

The 6.5 branch was fixed with commit a1e668592fe155bedc75a98a7f1c53afe162a094 and released as DREAM.3D 6.5.151
