### ISSUE TITLE
"ITK::Import Image Montage" crashes the application

### ISSUE THREAD

**Issue by Edodums** [BlueQuartzSoftware/DREAM3D#986]
Whenever I try to click the filter "ITK::Import Image Montage" the application closes itself. This doesn't happen instead with "ITK::Import Registered Image Montage".

I'm using a Windows 10, I wanted to try the ITK Montage module that is integrated within your application. But it seems I can't do it.

**Comment by imikejackson** [comment]
What version of DREAM.3D are you using? How many tiles in each axis are you trying to import?

**Comment by Edodums** [comment]
The latest downloadable version (6.5.160).
I admit it's first time I'm using it ( only for research purposes, I'm writing the Final exam Thesis  , and it's about Image Alignment and Stiching softwares and tools ).

If I read choose the filters to read an image it doesn't crash, an error dialog for the users would be perfect.
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/11229892/151938522-755e4d30-d353-469d-a585-fabd767f7d3c.png">

Now, the pipeline "works" but I don't know what I'm doing, tecnically the ITK-Montage module should be usable also for 2D.
Is there a way to produce an outuput stiched and aligned image via itk-montage, or am I totally wrong ?

**Comment by imikejackson** [comment]
Thank you for letting us know about the crashing bug. While I have fixed the bug and the importer will import the images the work that is include with version 6.5.x of DREAM.3D was a very early start on the montage feature and is not complete. Other than importing the data you cannot actually stitch the tiles into a montage.

The still in development version 6.6.x which can be downloaded from http://dream3d.bluequartz.net/binaries/experimental are builds from the latest development branches of DREAM.3D. That version includes 4 distinct montage import capabilities:

+ Zeiss AxioVision Import
+ Zeiss Zen Import
+ Import Fiji Montage
+ Import RoboMet Montage

Each of those importers has a specific configuration file that goes along with the data. There is no longer a generic montage importer. If you have a montage from another system or just a generic montage then the easiest would be to use the 'import Fiji Montage' and create the configuration file. The contents of the configuration file can be found at [https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/develop/Documentation/ITKImageProcessingFilters/ITKImportFijiMontage.md](https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/develop/Documentation/ITKImageProcessingFilters/ITKImportFijiMontage.md).

 A sample mosaic can be found at [https://github.com/BlueQuartzSoftware/ITKImageProcessing/tree/develop/Data/ITKImageProcessing/Montage/SampleMosaic](https://github.com/BlueQuartzSoftware/ITKImageProcessing/tree/develop/Data/ITKImageProcessing/Montage/SampleMosaic)

There are also some example pipelines that should go with it.

As of FEB 2 2022, *only* the Windows and Linux builds would have the montaging support. The macOS builds are somehow lacking the ability..

**Comment by Edodums** [comment]
Thank you very much, that was very helpful! 😄
