### ISSUE TITLE
FindSurfaceFeatures does not index into neighboring features properly when calculating surface features for a 2D geometry in the YZ plane.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/DREAM3D#988]
* Method find_surfacefeatures2D() uses getXPoints() to index into neighbors when it should really be using xPoints.  In the YZ plane, getXPoints() returns 1, so using getXPoints() is incorrect.

**Comment by imikejackson** [comment]
Fixed with 2db175d9a9f3d641e453a8c5bc5e0f15c47d1ff7
