### ISSUE TITLE
FindSurfaceFeatures incorrectly labels Feature 0 as a surface feature.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/DREAM3D#989]
This is because when striding through the featureIds array, there is no check to make sure that the current grain number is non-zero before determining whether the current grain number is a surface feature.

**Comment by joeykleingers** [comment]
This bug only appears when feature 0 exists in the feature ids array.

**Comment by imikejackson** [comment]
fixed by 2db175d9a9f3d641e453a8c5bc5e0f15c47d1ff7
