### ISSUE TITLE
Loading non-equiaxed grains generates equiaxed grains for larger structures

### ISSUE THREAD

**Issue by InigoEHowe** [BlueQuartzSoftware/DREAM3D#998]
For a model with dimensions 128x128x128 and resolution 1x1x1, when the grain structure is extracted and saved to a text file and then loaded back in to regenerate the same grain structure it generates a different structure. In the attached zip file are the two files containing the grain structures, in the original grains_structure.txt there are 46 grains. When this structure is loaded into DREAM3D and then the output is saved there are then 21 grains. I'm a pretty amateur user so I'm not sure what is going wrong. 

[fibrous_loading_issue.zip](https://github.com/BlueQuartzSoftware/DREAM3D/files/9071474/fibrous_loading_issue.zip)

**Comment by imikejackson** [comment]
What version of DREAM.3D are you using?

**Comment by imikejackson** [comment]
This can happen if the centers provided are very close to each other and you have selected a large grain size. In cases like this one grain can be "swallowed up" by another grain during the packing phase.

**Comment by InigoEHowe** [comment]
Hi Michael,

I'm using version 6.5.141. I guess the issue was that I had outputted the
grain statistics from a generated model so I was surprised that the
resulting structure was different. It does seem like the issue was that
grains were being swallowed up. The grains are large but quite flat, it was
my understanding that this was specified in the A B C ratio that you can
feed in.

Kind regards,

Inigo H
